### ISSUE TITLE
Gerber files seem to have plots offset

### ISSUE THREAD

**Issue by bastenhoor** [polykit/kosmo-spring-reverb-driver#2]
Hi, When uploading the plots folder to JLCPCB the drillholes seem te be offset.

**Comment by polykit** [comment]
Hi @bastenhoor thanks for letting me know. I uploaded new gerber files, please give it another try.

**Comment by bastenhoor** [comment]
Perfect! ;-)
Do you have the gerbers for the Eurorack version too perhaps? ;-)

**Comment by polykit** [comment]
> Perfect! ;-) Do you have the gerbers for the Eurorack version too perhaps? ;-)

No, sorry, only Kosmo as of now.

**Comment by bastenhoor** [comment]
No problem!

**Comment by bastenhoor** [comment]
One more question: do you have a link to the audio jacks? Mouser, AliExpress, whatever. Thanks!

**Comment by polykit** [comment]
> One more question: do you have a link to the audio jacks? Mouser, AliExpress, whatever. Thanks!

Any 6.35mm audio jack should do. I'm using https://www.aliexpress.com/item/32841081749.html
